// Anandi and Jagya were getting married again when they have achieved proper age. Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
// The generated blessing is a common subsequence of length K of the two blessings he has. Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
// Input Specification
// First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
// Output Specification
// Output consists of t lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.
// Constraint
// 1 <= t <= 50

// 1 <= length(b1) , length(b2) <= 100 

// 1 <= K <= 100
// Sample Input
// 2
// asdf
// asdf
// 3
// anandi
// jagya
// 3
// Sample Output
// 317
// 0

#include <bits/stdc++.h>
using namespace std;

int dp[101][101][101];
string s1,s2 ;

int happiness(int i , int j ,int k){
    
    
    if( i == s1.size() || j ==s2.size()){
        if( k>0){
            return INT_MIN ;
        }
        else{
            return 0;
        }
    }
    if (dp[i][j][k] != -1){
        return dp[i][j][k] ;
    }
    
    if(s1[i] == s2[j]){
        if (k>0){
            char temp = s1[i] ;
            dp[i][j][k] =  max(int(temp)+happiness(i+1,j+1,k-1),max(happiness(i+1,j,k),happiness(i,j+1,k))) ;
            return dp[i][j][k] ;
        }
        else{
            return 0 ;
        }
    }
    
    dp[i][j][k] = max(happiness(i+1,j,k),happiness(i,j+1,k)) ;
    
    return dp[i][j][k] ;
    
}

int main()
{
    int t;
    cin>>t ; 
    while(t--){
        memset(dp,-1,sizeof(dp)) ;
        cin>>s1;
        cin>>s2;
        int m=s1.size() ;
        int n=s2.size() ;
        int k;
        cin>>k;
        cout<<max(0,happiness(0,0,k))<<endl ;
    }
    return 0;
}
